### ISSUE TITLE
Fru parser segfaults on PVT Barreleye when reading IO Board vpd

### ISSUE THREAD

**Issue by anoo1** [openbmc/ipmi-fru-parser#19]
Reading vpd on IO board on PVT Barreleye seg faults and data is not added to the inventory.
System running 8.0.1 openbmc.

'''
root@barreleye:~# phosphor-read-eeprom --eeprom /sys/bus/i2c/devices/0-0050/eeprom --fruid 64
Segmentation fault
'''

**Comment by vishwabmc** [comment]
@williamspatrick  Please assign this to me..

@anoo1 Please give me the system and the build so I can recreate this.

**Comment by anoo1** [comment]
hi @vishwabmc , i'm working on this as part of syncing the mac address from vpd to u-boot since i need the parser to work so that it adds the info to the inventory. For reference it's recreatable in the PVT barreleye that we have, and any recent build, 1.0.1 would be the latest.

**Comment by anoo1** [comment]
VPD on IO board has been updated by the factory, closing.
