### ISSUE TITLE
fruid argument check type in readeeprom.cpp

### ISSUE THREAD

**Issue by dnbazhenov** [openbmc/ipmi-fru-parser#23]
Hi,

Found a copy-paste typo in readeeprom.cpp. The fruid_str parsed value is not actually checked for emptiness, the eeprom_str is checked instead. This may result in false-positive argument checks.

The attached patch fixes this typo.

Regards,
Dmitry
[0001-read-eeprom-fix-fruid-str-emptines-check.patch.gz](https://github.com/openbmc/ipmi-fru-parser/files/1172634/0001-read-eeprom-fix-fruid-str-emptines-check.patch.gz)

**Comment by anoo1** [comment]
Thanks! Do you mind posting this change on gerrit for review? Here are the instructions:
https://github.com/openbmc/docs/blob/master/contributing.md#submitting-changes-via-gerrit-server

**Comment by dnbazhenov** [comment]
Done.
