### ISSUE TITLE
ipmi-fru-parser should try to talk to phosphor-inventory-manager directly

### ISSUE THREAD

**Issue by kunyi731** [openbmc/ipmi-fru-parser#24]
During system boot time the mapper is under heavy load and could be flaky in returning the service name. Better to try call phosphor-inventory-manager directly if the mapper call fails.

**Comment by amboar** [comment]
Sounds like phosphor-inventory-manager could benefit from a well-known bus name? I started a discussion here about whether we could eliminate use of the mapper in some circumstances:

https://lists.ozlabs.org/pipermail/openbmc/2019-April/015889.html

We've baked this fall-back logic into code in other places in OpenBMC, however I'm not keen to see it spread. If we're going to fall-back in this manner we might as well avoid the mapper call altogether.

**Comment by kunyi731** [comment]
Given the difficulty of reproduction and we have a workaround (which is to retry parsing FRUs if failed), I'm going to close this issue.
