### ISSUE TITLE
【NetFn:0x0a ,Cmd:12<ipmiStorageWriteFruData> There are two function definitions，What are the differences between them?】

### ISSUE THREAD

**Issue by Chendd123** [openbmc/ipmi-fru-parser#29]
1. workspace\sources\phosphor-ipmi-host\dbus-sdr\storagecommands.cpp
    // <WRITE FRU Data>
    ipmi::registerHandler(ipmi::prioOpenBmcBase, ipmi::netFnStorage,
                          ipmi::storage::cmdWriteFruData,
                          ipmi::Privilege::Operator, ipmiStorageWriteFruData);

2. workspace\sources\phosphor-ipmi-fru\strgfnhandler.cpp
void register_netfn_storage_write_fru()
{
    std::printf("Registering NetFn:[0x%X], Cmd:[0x%X]\n", NETFUN_STORAGE,
                IPMI_CMD_WRITE_FRU_DATA);

    ipmi_register_callback(NETFUN_STORAGE, IPMI_CMD_WRITE_FRU_DATA, NULL,
                           ipmiStorageWriteFruData, SYSTEM_INTERFACE);
}

**Comment by williamspatrick** [comment]
Please stop opening issues for support questions.  You can use the mailing list or Discord.
